---
- name: "Preflight - Fail if target host is not stable for this Role."
  ansible.builtin.fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in nameserver_stable_os)

- name: "Include OS Family specific Variables."
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: "Include Distribution specific Variables."
  include_vars: "{{ ansible_distribution }}.yml"
  changed_when: 'false'
  failed_when: 'false'

- name: "Install Prerequisites."
  ansible.builtin.package:
    name: "{{ nameserver_prerequisites }}"
    state: present
  when: nameserver_installation | bool
  notify: enable nameserver

- name: "Disable systemd-resolved so it does not interfere."
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: 'no'

- name: "Include OS Family specific Playbook."
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
