---
- name: "Preflight - Fail if target host is not stable for this Role."
  ansible.builtin.fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in nameserver_stable_os)

- name: "Include OS Family specific Variables."
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: "Install prerequisites."
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nameserver_prerequisites }}"
  when: nameserver_installation | bool

- name: "Include OS Family specific Playbook."
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: "Include Configuration Deployment Playbook."
  ansible.builtin.include_tasks: "deployment.yml"

- name: "(Re)Start DNS Service."
  ansible.builtin.service:
    name: "{{ nameserver_service_name }}"
    state: restarted
    enabled: 'yes'
