---
- name: "Open up tcp/53 on firewall"
  ansible.posix.firewalld:
    service: dns
    permanent: 'yes'
    state: enabled
    immediate: 'yes'

#TODO: Which setype for Debian/Suse?
- name: "Deploy a version of named.conf that is dependent on the OS." #setype obtained by doing ls -Z /etc/named.conf on original file
  ansible.builtin.template:
    src: named.conf_{{ ansible_os_family }}.j2
    dest: /etc/named.conf
    group: named
    setype: named_conf_t
    mode: 0640
    validate: /sbin/named-checkconf %s

- name: "Deploy named.conf.local."
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/named/named.conf.local
    mode: 0644

- name: "Deploy Zone: {{ nameserver_default_zone }}."
  ansible.builtin.template:
    src: nameserver_default_zone.j2
    dest: /etc/named/zones/{{ nameserver_default_zone }}
    mode: 0644
    validate: /sbin/named-checkzone {{ nameserver_default_zone }} %s

- name: "Deploy Zone: {{ nameserver_reverse_zone }}."
  ansible.builtin.template:
    src: nameserver_reverse_zone.j2
    dest: /etc/named/zones/{{ nameserver_reverse_zone }}
    mode: 0644
    validate: /sbin/named-checkzone {{ nameserver_reverse_zone }} %s
